namespace GUI
{
    partial class FormRegistrarAsociado
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormRegistrarAsociado));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.txtMail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblCorreo = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDni = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDni = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPrincipalRegistrarAsociado = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblApellido = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblNombre = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnInicio = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnVolverOrden = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRegistarAsociado = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1Volver = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox2);
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(198, 112);
            this.bunifuPanel1.TabIndex = 68;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(0, 0);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(198, 112);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 6;
            this.pictureBox2.TabStop = false;
            // 
            // txtMail
            // 
            this.txtMail.AcceptsReturn = false;
            this.txtMail.AcceptsTab = false;
            this.txtMail.AnimationSpeed = 200;
            this.txtMail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMail.BackColor = System.Drawing.Color.Transparent;
            this.txtMail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMail.BackgroundImage")));
            this.txtMail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMail.BorderRadius = 1;
            this.txtMail.BorderThickness = 1;
            this.txtMail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMail.DefaultText = "";
            this.txtMail.FillColor = System.Drawing.Color.White;
            this.txtMail.HideSelection = true;
            this.txtMail.IconLeft = null;
            this.txtMail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMail.IconPadding = 10;
            this.txtMail.IconRight = null;
            this.txtMail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMail.Lines = new string[0];
            this.txtMail.Location = new System.Drawing.Point(310, 447);
            this.txtMail.MaxLength = 32767;
            this.txtMail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMail.Modified = false;
            this.txtMail.Multiline = false;
            this.txtMail.Name = "txtMail";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMail.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMail.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMail.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMail.OnIdleState = stateProperties4;
            this.txtMail.Padding = new System.Windows.Forms.Padding(3);
            this.txtMail.PasswordChar = '\0';
            this.txtMail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMail.PlaceholderText = "Enter text";
            this.txtMail.ReadOnly = false;
            this.txtMail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMail.SelectedText = "";
            this.txtMail.SelectionLength = 0;
            this.txtMail.SelectionStart = 0;
            this.txtMail.ShortcutsEnabled = true;
            this.txtMail.Size = new System.Drawing.Size(260, 37);
            this.txtMail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMail.TabIndex = 67;
            this.txtMail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMail.TextMarginBottom = 0;
            this.txtMail.TextMarginLeft = 3;
            this.txtMail.TextMarginTop = 0;
            this.txtMail.TextPlaceholder = "Enter text";
            this.txtMail.UseSystemPasswordChar = false;
            this.txtMail.WordWrap = true;
            // 
            // lblCorreo
            // 
            this.lblCorreo.AllowParentOverrides = false;
            this.lblCorreo.AutoEllipsis = false;
            this.lblCorreo.CursorType = null;
            this.lblCorreo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblCorreo.ForeColor = System.Drawing.SystemColors.Control;
            this.lblCorreo.Location = new System.Drawing.Point(310, 426);
            this.lblCorreo.Name = "lblCorreo";
            this.lblCorreo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblCorreo.Size = new System.Drawing.Size(36, 15);
            this.lblCorreo.TabIndex = 66;
            this.lblCorreo.Text = "Correo";
            this.lblCorreo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblCorreo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtNombre
            // 
            this.txtNombre.AcceptsReturn = false;
            this.txtNombre.AcceptsTab = false;
            this.txtNombre.AnimationSpeed = 200;
            this.txtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombre.BackgroundImage")));
            this.txtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombre.BorderRadius = 1;
            this.txtNombre.BorderThickness = 1;
            this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNombre.DefaultText = "";
            this.txtNombre.FillColor = System.Drawing.Color.White;
            this.txtNombre.HideSelection = true;
            this.txtNombre.IconLeft = null;
            this.txtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.IconPadding = 10;
            this.txtNombre.IconRight = null;
            this.txtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.Lines = new string[0];
            this.txtNombre.Location = new System.Drawing.Point(310, 299);
            this.txtNombre.MaxLength = 32767;
            this.txtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombre.Modified = false;
            this.txtNombre.Multiline = false;
            this.txtNombre.Name = "txtNombre";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombre.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnIdleState = stateProperties8;
            this.txtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombre.PasswordChar = '\0';
            this.txtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombre.PlaceholderText = "Enter text";
            this.txtNombre.ReadOnly = false;
            this.txtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombre.SelectedText = "";
            this.txtNombre.SelectionLength = 0;
            this.txtNombre.SelectionStart = 0;
            this.txtNombre.ShortcutsEnabled = true;
            this.txtNombre.Size = new System.Drawing.Size(260, 37);
            this.txtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombre.TabIndex = 65;
            this.txtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombre.TextMarginBottom = 0;
            this.txtNombre.TextMarginLeft = 3;
            this.txtNombre.TextMarginTop = 0;
            this.txtNombre.TextPlaceholder = "Enter text";
            this.txtNombre.UseSystemPasswordChar = false;
            this.txtNombre.WordWrap = true;
            // 
            // txtApellido
            // 
            this.txtApellido.AcceptsReturn = false;
            this.txtApellido.AcceptsTab = false;
            this.txtApellido.AnimationSpeed = 200;
            this.txtApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtApellido.BackColor = System.Drawing.Color.Transparent;
            this.txtApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtApellido.BackgroundImage")));
            this.txtApellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtApellido.BorderRadius = 1;
            this.txtApellido.BorderThickness = 1;
            this.txtApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtApellido.DefaultText = "";
            this.txtApellido.FillColor = System.Drawing.Color.White;
            this.txtApellido.HideSelection = true;
            this.txtApellido.IconLeft = null;
            this.txtApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellido.IconPadding = 10;
            this.txtApellido.IconRight = null;
            this.txtApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellido.Lines = new string[0];
            this.txtApellido.Location = new System.Drawing.Point(310, 375);
            this.txtApellido.MaxLength = 32767;
            this.txtApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtApellido.Modified = false;
            this.txtApellido.Multiline = false;
            this.txtApellido.Name = "txtApellido";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellido.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtApellido.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellido.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellido.OnIdleState = stateProperties12;
            this.txtApellido.Padding = new System.Windows.Forms.Padding(3);
            this.txtApellido.PasswordChar = '\0';
            this.txtApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtApellido.PlaceholderText = "Enter text";
            this.txtApellido.ReadOnly = false;
            this.txtApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtApellido.SelectedText = "";
            this.txtApellido.SelectionLength = 0;
            this.txtApellido.SelectionStart = 0;
            this.txtApellido.ShortcutsEnabled = true;
            this.txtApellido.Size = new System.Drawing.Size(260, 37);
            this.txtApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtApellido.TabIndex = 64;
            this.txtApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtApellido.TextMarginBottom = 0;
            this.txtApellido.TextMarginLeft = 3;
            this.txtApellido.TextMarginTop = 0;
            this.txtApellido.TextPlaceholder = "Enter text";
            this.txtApellido.UseSystemPasswordChar = false;
            this.txtApellido.WordWrap = true;
            // 
            // txtDni
            // 
            this.txtDni.AcceptsReturn = false;
            this.txtDni.AcceptsTab = false;
            this.txtDni.AnimationSpeed = 200;
            this.txtDni.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDni.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDni.BackColor = System.Drawing.Color.Transparent;
            this.txtDni.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDni.BackgroundImage")));
            this.txtDni.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDni.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDni.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDni.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDni.BorderRadius = 1;
            this.txtDni.BorderThickness = 1;
            this.txtDni.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDni.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDni.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDni.DefaultText = "";
            this.txtDni.FillColor = System.Drawing.Color.White;
            this.txtDni.HideSelection = true;
            this.txtDni.IconLeft = null;
            this.txtDni.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDni.IconPadding = 10;
            this.txtDni.IconRight = null;
            this.txtDni.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDni.Lines = new string[0];
            this.txtDni.Location = new System.Drawing.Point(310, 228);
            this.txtDni.MaxLength = 32767;
            this.txtDni.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDni.Modified = false;
            this.txtDni.Multiline = false;
            this.txtDni.Name = "txtDni";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDni.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDni.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDni.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDni.OnIdleState = stateProperties16;
            this.txtDni.Padding = new System.Windows.Forms.Padding(3);
            this.txtDni.PasswordChar = '\0';
            this.txtDni.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDni.PlaceholderText = "Enter text";
            this.txtDni.ReadOnly = false;
            this.txtDni.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDni.SelectedText = "";
            this.txtDni.SelectionLength = 0;
            this.txtDni.SelectionStart = 0;
            this.txtDni.ShortcutsEnabled = true;
            this.txtDni.Size = new System.Drawing.Size(260, 37);
            this.txtDni.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDni.TabIndex = 63;
            this.txtDni.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDni.TextMarginBottom = 0;
            this.txtDni.TextMarginLeft = 3;
            this.txtDni.TextMarginTop = 0;
            this.txtDni.TextPlaceholder = "Enter text";
            this.txtDni.UseSystemPasswordChar = false;
            this.txtDni.WordWrap = true;
            // 
            // lblDni
            // 
            this.lblDni.AllowParentOverrides = false;
            this.lblDni.AutoEllipsis = false;
            this.lblDni.CursorType = null;
            this.lblDni.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblDni.ForeColor = System.Drawing.SystemColors.Control;
            this.lblDni.Location = new System.Drawing.Point(310, 207);
            this.lblDni.Name = "lblDni";
            this.lblDni.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblDni.Size = new System.Drawing.Size(18, 15);
            this.lblDni.TabIndex = 62;
            this.lblDni.Text = "Dni";
            this.lblDni.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblDni.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblPrincipalRegistrarAsociado
            // 
            this.lblPrincipalRegistrarAsociado.AllowParentOverrides = false;
            this.lblPrincipalRegistrarAsociado.AutoEllipsis = false;
            this.lblPrincipalRegistrarAsociado.AutoSize = false;
            this.lblPrincipalRegistrarAsociado.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblPrincipalRegistrarAsociado.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblPrincipalRegistrarAsociado.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblPrincipalRegistrarAsociado.Font = new System.Drawing.Font("Arial Rounded MT Bold", 20.25F, System.Drawing.FontStyle.Bold);
            this.lblPrincipalRegistrarAsociado.ForeColor = System.Drawing.SystemColors.Control;
            this.lblPrincipalRegistrarAsociado.Location = new System.Drawing.Point(0, 0);
            this.lblPrincipalRegistrarAsociado.Name = "lblPrincipalRegistrarAsociado";
            this.lblPrincipalRegistrarAsociado.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPrincipalRegistrarAsociado.Size = new System.Drawing.Size(900, 112);
            this.lblPrincipalRegistrarAsociado.TabIndex = 61;
            this.lblPrincipalRegistrarAsociado.Text = "REGISTRAR ASOCIADO";
            this.lblPrincipalRegistrarAsociado.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblPrincipalRegistrarAsociado.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblApellido
            // 
            this.lblApellido.AllowParentOverrides = false;
            this.lblApellido.AutoEllipsis = false;
            this.lblApellido.CursorType = null;
            this.lblApellido.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblApellido.ForeColor = System.Drawing.SystemColors.Control;
            this.lblApellido.Location = new System.Drawing.Point(310, 354);
            this.lblApellido.Name = "lblApellido";
            this.lblApellido.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblApellido.Size = new System.Drawing.Size(44, 15);
            this.lblApellido.TabIndex = 60;
            this.lblApellido.Text = "Apellido";
            this.lblApellido.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblApellido.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblNombre
            // 
            this.lblNombre.AllowParentOverrides = false;
            this.lblNombre.AutoEllipsis = false;
            this.lblNombre.CursorType = null;
            this.lblNombre.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblNombre.ForeColor = System.Drawing.SystemColors.Control;
            this.lblNombre.Location = new System.Drawing.Point(310, 278);
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblNombre.Size = new System.Drawing.Size(44, 15);
            this.lblNombre.TabIndex = 59;
            this.lblNombre.Text = "Nombre";
            this.lblNombre.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblNombre.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnInicio
            // 
            this.btnInicio.AllowAnimations = true;
            this.btnInicio.AllowMouseEffects = true;
            this.btnInicio.AllowToggling = false;
            this.btnInicio.AnimationSpeed = 200;
            this.btnInicio.AutoGenerateColors = false;
            this.btnInicio.AutoRoundBorders = false;
            this.btnInicio.AutoSizeLeftIcon = true;
            this.btnInicio.AutoSizeRightIcon = true;
            this.btnInicio.BackColor = System.Drawing.Color.Transparent;
            this.btnInicio.BackColor1 = System.Drawing.Color.Red;
            this.btnInicio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInicio.BackgroundImage")));
            this.btnInicio.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.ButtonText = "←";
            this.btnInicio.ButtonTextMarginLeft = 0;
            this.btnInicio.ColorContrastOnClick = 45;
            this.btnInicio.ColorContrastOnHover = 45;
            this.btnInicio.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnInicio.CustomizableEdges = borderEdges1;
            this.btnInicio.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInicio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInicio.Font = new System.Drawing.Font("Arial Black", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInicio.ForeColor = System.Drawing.Color.White;
            this.btnInicio.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInicio.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInicio.IconMarginLeft = 11;
            this.btnInicio.IconPadding = 10;
            this.btnInicio.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInicio.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInicio.IconSize = 25;
            this.btnInicio.IdleBorderColor = System.Drawing.Color.Red;
            this.btnInicio.IdleBorderRadius = 1;
            this.btnInicio.IdleBorderThickness = 1;
            this.btnInicio.IdleFillColor = System.Drawing.Color.Red;
            this.btnInicio.IdleIconLeftImage = null;
            this.btnInicio.IdleIconRightImage = null;
            this.btnInicio.IndicateFocus = false;
            this.btnInicio.Location = new System.Drawing.Point(853, 26);
            this.btnInicio.Name = "btnInicio";
            this.btnInicio.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.OnDisabledState.BorderRadius = 1;
            this.btnInicio.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnDisabledState.BorderThickness = 1;
            this.btnInicio.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.OnDisabledState.IconLeftImage = null;
            this.btnInicio.OnDisabledState.IconRightImage = null;
            this.btnInicio.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.onHoverState.BorderRadius = 1;
            this.btnInicio.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.onHoverState.BorderThickness = 1;
            this.btnInicio.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.onHoverState.IconLeftImage = null;
            this.btnInicio.onHoverState.IconRightImage = null;
            this.btnInicio.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnInicio.OnIdleState.BorderRadius = 1;
            this.btnInicio.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnIdleState.BorderThickness = 1;
            this.btnInicio.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnInicio.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.OnIdleState.IconLeftImage = null;
            this.btnInicio.OnIdleState.IconRightImage = null;
            this.btnInicio.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.OnPressedState.BorderRadius = 1;
            this.btnInicio.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnPressedState.BorderThickness = 1;
            this.btnInicio.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.OnPressedState.IconLeftImage = null;
            this.btnInicio.OnPressedState.IconRightImage = null;
            this.btnInicio.Size = new System.Drawing.Size(31, 26);
            this.btnInicio.TabIndex = 71;
            this.btnInicio.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnInicio.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInicio.TextMarginLeft = 0;
            this.btnInicio.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInicio.UseDefaultRadiusAndThickness = true;
            // 
            // btnVolverOrden
            // 
            this.btnVolverOrden.AllowAnimations = true;
            this.btnVolverOrden.AllowMouseEffects = true;
            this.btnVolverOrden.AllowToggling = false;
            this.btnVolverOrden.AnimationSpeed = 200;
            this.btnVolverOrden.AutoGenerateColors = false;
            this.btnVolverOrden.AutoRoundBorders = false;
            this.btnVolverOrden.AutoSizeLeftIcon = true;
            this.btnVolverOrden.AutoSizeRightIcon = true;
            this.btnVolverOrden.BackColor = System.Drawing.Color.Transparent;
            this.btnVolverOrden.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnVolverOrden.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVolverOrden.BackgroundImage")));
            this.btnVolverOrden.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVolverOrden.ButtonText = "Volver a la Orden de Pago";
            this.btnVolverOrden.ButtonTextMarginLeft = 0;
            this.btnVolverOrden.ColorContrastOnClick = 45;
            this.btnVolverOrden.ColorContrastOnHover = 45;
            this.btnVolverOrden.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnVolverOrden.CustomizableEdges = borderEdges2;
            this.btnVolverOrden.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVolverOrden.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVolverOrden.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVolverOrden.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVolverOrden.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnVolverOrden.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVolverOrden.ForeColor = System.Drawing.Color.White;
            this.btnVolverOrden.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVolverOrden.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVolverOrden.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVolverOrden.IconMarginLeft = 11;
            this.btnVolverOrden.IconPadding = 10;
            this.btnVolverOrden.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVolverOrden.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVolverOrden.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVolverOrden.IconSize = 25;
            this.btnVolverOrden.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnVolverOrden.IdleBorderRadius = 1;
            this.btnVolverOrden.IdleBorderThickness = 1;
            this.btnVolverOrden.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnVolverOrden.IdleIconLeftImage = null;
            this.btnVolverOrden.IdleIconRightImage = null;
            this.btnVolverOrden.IndicateFocus = false;
            this.btnVolverOrden.Location = new System.Drawing.Point(718, 650);
            this.btnVolverOrden.Name = "btnVolverOrden";
            this.btnVolverOrden.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVolverOrden.OnDisabledState.BorderRadius = 1;
            this.btnVolverOrden.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVolverOrden.OnDisabledState.BorderThickness = 1;
            this.btnVolverOrden.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVolverOrden.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVolverOrden.OnDisabledState.IconLeftImage = null;
            this.btnVolverOrden.OnDisabledState.IconRightImage = null;
            this.btnVolverOrden.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVolverOrden.onHoverState.BorderRadius = 1;
            this.btnVolverOrden.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVolverOrden.onHoverState.BorderThickness = 1;
            this.btnVolverOrden.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVolverOrden.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVolverOrden.onHoverState.IconLeftImage = null;
            this.btnVolverOrden.onHoverState.IconRightImage = null;
            this.btnVolverOrden.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnVolverOrden.OnIdleState.BorderRadius = 1;
            this.btnVolverOrden.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVolverOrden.OnIdleState.BorderThickness = 1;
            this.btnVolverOrden.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnVolverOrden.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVolverOrden.OnIdleState.IconLeftImage = null;
            this.btnVolverOrden.OnIdleState.IconRightImage = null;
            this.btnVolverOrden.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVolverOrden.OnPressedState.BorderRadius = 1;
            this.btnVolverOrden.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVolverOrden.OnPressedState.BorderThickness = 1;
            this.btnVolverOrden.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVolverOrden.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVolverOrden.OnPressedState.IconLeftImage = null;
            this.btnVolverOrden.OnPressedState.IconRightImage = null;
            this.btnVolverOrden.Size = new System.Drawing.Size(154, 25);
            this.btnVolverOrden.TabIndex = 70;
            this.btnVolverOrden.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVolverOrden.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVolverOrden.TextMarginLeft = 0;
            this.btnVolverOrden.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVolverOrden.UseDefaultRadiusAndThickness = true;
            this.btnVolverOrden.Visible = false;
            this.btnVolverOrden.Click += new System.EventHandler(this.btnVolverOrden_Click);
            // 
            // btnRegistarAsociado
            // 
            this.btnRegistarAsociado.AllowAnimations = true;
            this.btnRegistarAsociado.AllowMouseEffects = true;
            this.btnRegistarAsociado.AllowToggling = false;
            this.btnRegistarAsociado.AnimationSpeed = 200;
            this.btnRegistarAsociado.AutoGenerateColors = false;
            this.btnRegistarAsociado.AutoRoundBorders = false;
            this.btnRegistarAsociado.AutoSizeLeftIcon = true;
            this.btnRegistarAsociado.AutoSizeRightIcon = true;
            this.btnRegistarAsociado.BackColor = System.Drawing.Color.Transparent;
            this.btnRegistarAsociado.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnRegistarAsociado.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRegistarAsociado.BackgroundImage")));
            this.btnRegistarAsociado.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistarAsociado.ButtonText = "Registrar ";
            this.btnRegistarAsociado.ButtonTextMarginLeft = 0;
            this.btnRegistarAsociado.ColorContrastOnClick = 45;
            this.btnRegistarAsociado.ColorContrastOnHover = 45;
            this.btnRegistarAsociado.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnRegistarAsociado.CustomizableEdges = borderEdges3;
            this.btnRegistarAsociado.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRegistarAsociado.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegistarAsociado.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegistarAsociado.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegistarAsociado.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRegistarAsociado.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRegistarAsociado.ForeColor = System.Drawing.Color.White;
            this.btnRegistarAsociado.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRegistarAsociado.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegistarAsociado.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRegistarAsociado.IconMarginLeft = 11;
            this.btnRegistarAsociado.IconPadding = 10;
            this.btnRegistarAsociado.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRegistarAsociado.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRegistarAsociado.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRegistarAsociado.IconSize = 25;
            this.btnRegistarAsociado.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRegistarAsociado.IdleBorderRadius = 1;
            this.btnRegistarAsociado.IdleBorderThickness = 1;
            this.btnRegistarAsociado.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnRegistarAsociado.IdleIconLeftImage = null;
            this.btnRegistarAsociado.IdleIconRightImage = null;
            this.btnRegistarAsociado.IndicateFocus = false;
            this.btnRegistarAsociado.Location = new System.Drawing.Point(358, 504);
            this.btnRegistarAsociado.Name = "btnRegistarAsociado";
            this.btnRegistarAsociado.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRegistarAsociado.OnDisabledState.BorderRadius = 1;
            this.btnRegistarAsociado.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistarAsociado.OnDisabledState.BorderThickness = 1;
            this.btnRegistarAsociado.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRegistarAsociado.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRegistarAsociado.OnDisabledState.IconLeftImage = null;
            this.btnRegistarAsociado.OnDisabledState.IconRightImage = null;
            this.btnRegistarAsociado.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRegistarAsociado.onHoverState.BorderRadius = 1;
            this.btnRegistarAsociado.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistarAsociado.onHoverState.BorderThickness = 1;
            this.btnRegistarAsociado.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRegistarAsociado.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRegistarAsociado.onHoverState.IconLeftImage = null;
            this.btnRegistarAsociado.onHoverState.IconRightImage = null;
            this.btnRegistarAsociado.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRegistarAsociado.OnIdleState.BorderRadius = 1;
            this.btnRegistarAsociado.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistarAsociado.OnIdleState.BorderThickness = 1;
            this.btnRegistarAsociado.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnRegistarAsociado.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRegistarAsociado.OnIdleState.IconLeftImage = null;
            this.btnRegistarAsociado.OnIdleState.IconRightImage = null;
            this.btnRegistarAsociado.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRegistarAsociado.OnPressedState.BorderRadius = 1;
            this.btnRegistarAsociado.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRegistarAsociado.OnPressedState.BorderThickness = 1;
            this.btnRegistarAsociado.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRegistarAsociado.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRegistarAsociado.OnPressedState.IconLeftImage = null;
            this.btnRegistarAsociado.OnPressedState.IconRightImage = null;
            this.btnRegistarAsociado.Size = new System.Drawing.Size(154, 25);
            this.btnRegistarAsociado.TabIndex = 69;
            this.btnRegistarAsociado.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRegistarAsociado.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRegistarAsociado.TextMarginLeft = 0;
            this.btnRegistarAsociado.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRegistarAsociado.UseDefaultRadiusAndThickness = true;
            this.btnRegistarAsociado.Click += new System.EventHandler(this.btnRegistarCliente_Click);
            // 
            // bunifuButton1Volver
            // 
            this.bunifuButton1Volver.AllowAnimations = true;
            this.bunifuButton1Volver.AllowMouseEffects = true;
            this.bunifuButton1Volver.AllowToggling = false;
            this.bunifuButton1Volver.AnimationSpeed = 200;
            this.bunifuButton1Volver.AutoGenerateColors = false;
            this.bunifuButton1Volver.AutoRoundBorders = false;
            this.bunifuButton1Volver.AutoSizeLeftIcon = true;
            this.bunifuButton1Volver.AutoSizeRightIcon = true;
            this.bunifuButton1Volver.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1Volver.BackColor1 = System.Drawing.Color.Red;
            this.bunifuButton1Volver.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1Volver.BackgroundImage")));
            this.bunifuButton1Volver.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1Volver.ButtonText = "←";
            this.bunifuButton1Volver.ButtonTextMarginLeft = 0;
            this.bunifuButton1Volver.ColorContrastOnClick = 45;
            this.bunifuButton1Volver.ColorContrastOnHover = 45;
            this.bunifuButton1Volver.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton1Volver.CustomizableEdges = borderEdges4;
            this.bunifuButton1Volver.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1Volver.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1Volver.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1Volver.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1Volver.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1Volver.Font = new System.Drawing.Font("Arial Black", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1Volver.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1Volver.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1Volver.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1Volver.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1Volver.IconMarginLeft = 11;
            this.bunifuButton1Volver.IconPadding = 10;
            this.bunifuButton1Volver.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1Volver.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1Volver.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1Volver.IconSize = 25;
            this.bunifuButton1Volver.IdleBorderColor = System.Drawing.Color.Red;
            this.bunifuButton1Volver.IdleBorderRadius = 1;
            this.bunifuButton1Volver.IdleBorderThickness = 1;
            this.bunifuButton1Volver.IdleFillColor = System.Drawing.Color.Red;
            this.bunifuButton1Volver.IdleIconLeftImage = null;
            this.bunifuButton1Volver.IdleIconRightImage = null;
            this.bunifuButton1Volver.IndicateFocus = false;
            this.bunifuButton1Volver.Location = new System.Drawing.Point(869, 0);
            this.bunifuButton1Volver.Name = "bunifuButton1Volver";
            this.bunifuButton1Volver.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1Volver.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1Volver.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1Volver.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1Volver.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1Volver.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1Volver.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1Volver.OnDisabledState.IconRightImage = null;
            this.bunifuButton1Volver.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton1Volver.onHoverState.BorderRadius = 1;
            this.bunifuButton1Volver.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1Volver.onHoverState.BorderThickness = 1;
            this.bunifuButton1Volver.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton1Volver.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1Volver.onHoverState.IconLeftImage = null;
            this.bunifuButton1Volver.onHoverState.IconRightImage = null;
            this.bunifuButton1Volver.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.bunifuButton1Volver.OnIdleState.BorderRadius = 1;
            this.bunifuButton1Volver.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1Volver.OnIdleState.BorderThickness = 1;
            this.bunifuButton1Volver.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.bunifuButton1Volver.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1Volver.OnIdleState.IconLeftImage = null;
            this.bunifuButton1Volver.OnIdleState.IconRightImage = null;
            this.bunifuButton1Volver.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton1Volver.OnPressedState.BorderRadius = 1;
            this.bunifuButton1Volver.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1Volver.OnPressedState.BorderThickness = 1;
            this.bunifuButton1Volver.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bunifuButton1Volver.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1Volver.OnPressedState.IconLeftImage = null;
            this.bunifuButton1Volver.OnPressedState.IconRightImage = null;
            this.bunifuButton1Volver.Size = new System.Drawing.Size(31, 26);
            this.bunifuButton1Volver.TabIndex = 72;
            this.bunifuButton1Volver.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.bunifuButton1Volver.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1Volver.TextMarginLeft = 0;
            this.bunifuButton1Volver.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1Volver.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1Volver.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // FormRegistrarAsociado
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(28)))), ((int)(((byte)(82)))));
            this.ClientSize = new System.Drawing.Size(900, 700);
            this.Controls.Add(this.bunifuButton1Volver);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.txtMail);
            this.Controls.Add(this.lblCorreo);
            this.Controls.Add(this.txtNombre);
            this.Controls.Add(this.txtApellido);
            this.Controls.Add(this.txtDni);
            this.Controls.Add(this.lblDni);
            this.Controls.Add(this.lblPrincipalRegistrarAsociado);
            this.Controls.Add(this.lblApellido);
            this.Controls.Add(this.lblNombre);
            this.Controls.Add(this.btnInicio);
            this.Controls.Add(this.btnVolverOrden);
            this.Controls.Add(this.btnRegistarAsociado);
            this.Name = "FormRegistrarAsociado";
            this.Text = "FormRegistrarAsociado";
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtMail;
        private Bunifu.UI.WinForms.BunifuLabel lblCorreo;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtApellido;
        private Bunifu.UI.WinForms.BunifuTextBox txtDni;
        private Bunifu.UI.WinForms.BunifuLabel lblDni;
        private Bunifu.UI.WinForms.BunifuLabel lblPrincipalRegistrarAsociado;
        private Bunifu.UI.WinForms.BunifuLabel lblApellido;
        private Bunifu.UI.WinForms.BunifuLabel lblNombre;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInicio;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnVolverOrden;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRegistarAsociado;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1Volver;
    }
}