namespace GUI
{
    partial class FormGestionUsuario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGestionUsuario));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.DGusers = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnModificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAgregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TxtDni = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblNumeroUsuarios = new System.Windows.Forms.Label();
            this.lblCantUser = new System.Windows.Forms.Label();
            this.btnDesbloquear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLimpiarSeleccion = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnInicio = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.cmbRoles = new System.Windows.Forms.ComboBox();
            ((System.ComponentModel.ISupportInitialize)(this.DGusers)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // DGusers
            // 
            this.DGusers.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.DGusers.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.DGusers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.DGusers.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DGusers.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.DGusers.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.DGusers.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DGusers.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.DGusers.ColumnHeadersHeight = 40;
            this.DGusers.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.DGusers.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DGusers.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DGusers.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DGusers.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.DGusers.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.DGusers.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DGusers.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.DGusers.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.DGusers.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.DGusers.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.DGusers.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.DGusers.CurrentTheme.Name = null;
            this.DGusers.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.DGusers.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DGusers.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DGusers.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DGusers.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.DGusers.DefaultCellStyle = dataGridViewCellStyle3;
            this.DGusers.EnableHeadersVisualStyles = false;
            this.DGusers.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DGusers.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.DGusers.HeaderBgColor = System.Drawing.Color.Empty;
            this.DGusers.HeaderForeColor = System.Drawing.Color.White;
            this.DGusers.Location = new System.Drawing.Point(27, 140);
            this.DGusers.MultiSelect = false;
            this.DGusers.Name = "DGusers";
            this.DGusers.ReadOnly = true;
            this.DGusers.RowHeadersVisible = false;
            this.DGusers.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.DGusers.RowTemplate.Height = 40;
            this.DGusers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DGusers.Size = new System.Drawing.Size(648, 348);
            this.DGusers.TabIndex = 0;
            this.DGusers.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.DGusers.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.DGusers_CellContentClick);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuLabel1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 20.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.SystemColors.Control;
            this.bunifuLabel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(900, 112);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "GESTIÓN DE USUARIOS";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnModificar
            // 
            this.btnModificar.AllowAnimations = true;
            this.btnModificar.AllowMouseEffects = true;
            this.btnModificar.AllowToggling = false;
            this.btnModificar.AnimationSpeed = 200;
            this.btnModificar.AutoGenerateColors = false;
            this.btnModificar.AutoRoundBorders = false;
            this.btnModificar.AutoSizeLeftIcon = true;
            this.btnModificar.AutoSizeRightIcon = true;
            this.btnModificar.BackColor = System.Drawing.Color.Transparent;
            this.btnModificar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnModificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModificar.BackgroundImage")));
            this.btnModificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.ButtonText = "Modificar";
            this.btnModificar.ButtonTextMarginLeft = 0;
            this.btnModificar.ColorContrastOnClick = 45;
            this.btnModificar.ColorContrastOnHover = 45;
            this.btnModificar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnModificar.CustomizableEdges = borderEdges1;
            this.btnModificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificar.Enabled = false;
            this.btnModificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModificar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnModificar.ForeColor = System.Drawing.Color.White;
            this.btnModificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModificar.IconMarginLeft = 11;
            this.btnModificar.IconPadding = 10;
            this.btnModificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModificar.IconSize = 25;
            this.btnModificar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.IdleBorderRadius = 1;
            this.btnModificar.IdleBorderThickness = 1;
            this.btnModificar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.IdleIconLeftImage = null;
            this.btnModificar.IdleIconRightImage = null;
            this.btnModificar.IndicateFocus = false;
            this.btnModificar.Location = new System.Drawing.Point(700, 358);
            this.btnModificar.Name = "btnModificar";
            this.btnModificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificar.OnDisabledState.BorderRadius = 1;
            this.btnModificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnDisabledState.BorderThickness = 1;
            this.btnModificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificar.OnDisabledState.IconLeftImage = null;
            this.btnModificar.OnDisabledState.IconRightImage = null;
            this.btnModificar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificar.onHoverState.BorderRadius = 1;
            this.btnModificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.onHoverState.BorderThickness = 1;
            this.btnModificar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModificar.onHoverState.IconLeftImage = null;
            this.btnModificar.onHoverState.IconRightImage = null;
            this.btnModificar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.OnIdleState.BorderRadius = 1;
            this.btnModificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnIdleState.BorderThickness = 1;
            this.btnModificar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModificar.OnIdleState.IconLeftImage = null;
            this.btnModificar.OnIdleState.IconRightImage = null;
            this.btnModificar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificar.OnPressedState.BorderRadius = 1;
            this.btnModificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnPressedState.BorderThickness = 1;
            this.btnModificar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModificar.OnPressedState.IconLeftImage = null;
            this.btnModificar.OnPressedState.IconRightImage = null;
            this.btnModificar.Size = new System.Drawing.Size(150, 39);
            this.btnModificar.TabIndex = 18;
            this.btnModificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModificar.TextMarginLeft = 0;
            this.btnModificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModificar.UseDefaultRadiusAndThickness = true;
            this.btnModificar.Click += new System.EventHandler(this.btnModificar_Click);
            // 
            // btnEliminar
            // 
            this.btnEliminar.AllowAnimations = true;
            this.btnEliminar.AllowMouseEffects = true;
            this.btnEliminar.AllowToggling = false;
            this.btnEliminar.AnimationSpeed = 200;
            this.btnEliminar.AutoGenerateColors = false;
            this.btnEliminar.AutoRoundBorders = false;
            this.btnEliminar.AutoSizeLeftIcon = true;
            this.btnEliminar.AutoSizeRightIcon = true;
            this.btnEliminar.BackColor = System.Drawing.Color.Transparent;
            this.btnEliminar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnEliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEliminar.BackgroundImage")));
            this.btnEliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.ButtonText = "Eliminar";
            this.btnEliminar.ButtonTextMarginLeft = 0;
            this.btnEliminar.ColorContrastOnClick = 45;
            this.btnEliminar.ColorContrastOnHover = 45;
            this.btnEliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnEliminar.CustomizableEdges = borderEdges2;
            this.btnEliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminar.Enabled = false;
            this.btnEliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEliminar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnEliminar.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEliminar.IconMarginLeft = 11;
            this.btnEliminar.IconPadding = 10;
            this.btnEliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEliminar.IconSize = 25;
            this.btnEliminar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEliminar.IdleBorderRadius = 1;
            this.btnEliminar.IdleBorderThickness = 1;
            this.btnEliminar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnEliminar.IdleIconLeftImage = null;
            this.btnEliminar.IdleIconRightImage = null;
            this.btnEliminar.IndicateFocus = false;
            this.btnEliminar.Location = new System.Drawing.Point(700, 238);
            this.btnEliminar.Name = "btnEliminar";
            this.btnEliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEliminar.OnDisabledState.BorderRadius = 1;
            this.btnEliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.OnDisabledState.BorderThickness = 1;
            this.btnEliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEliminar.OnDisabledState.IconLeftImage = null;
            this.btnEliminar.OnDisabledState.IconRightImage = null;
            this.btnEliminar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEliminar.onHoverState.BorderRadius = 1;
            this.btnEliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.onHoverState.BorderThickness = 1;
            this.btnEliminar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.onHoverState.IconLeftImage = null;
            this.btnEliminar.onHoverState.IconRightImage = null;
            this.btnEliminar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEliminar.OnIdleState.BorderRadius = 1;
            this.btnEliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.OnIdleState.BorderThickness = 1;
            this.btnEliminar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.OnIdleState.IconLeftImage = null;
            this.btnEliminar.OnIdleState.IconRightImage = null;
            this.btnEliminar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEliminar.OnPressedState.BorderRadius = 1;
            this.btnEliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEliminar.OnPressedState.BorderThickness = 1;
            this.btnEliminar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEliminar.OnPressedState.IconLeftImage = null;
            this.btnEliminar.OnPressedState.IconRightImage = null;
            this.btnEliminar.Size = new System.Drawing.Size(150, 39);
            this.btnEliminar.TabIndex = 17;
            this.btnEliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEliminar.TextMarginLeft = 0;
            this.btnEliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEliminar.UseDefaultRadiusAndThickness = true;
            this.btnEliminar.Click += new System.EventHandler(this.btnEliminar_Click);
            // 
            // btnAgregar
            // 
            this.btnAgregar.AllowAnimations = true;
            this.btnAgregar.AllowMouseEffects = true;
            this.btnAgregar.AllowToggling = false;
            this.btnAgregar.AnimationSpeed = 200;
            this.btnAgregar.AutoGenerateColors = false;
            this.btnAgregar.AutoRoundBorders = false;
            this.btnAgregar.AutoSizeLeftIcon = true;
            this.btnAgregar.AutoSizeRightIcon = true;
            this.btnAgregar.BackColor = System.Drawing.Color.Transparent;
            this.btnAgregar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnAgregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAgregar.BackgroundImage")));
            this.btnAgregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.ButtonText = "Agregar";
            this.btnAgregar.ButtonTextMarginLeft = 0;
            this.btnAgregar.ColorContrastOnClick = 45;
            this.btnAgregar.ColorContrastOnHover = 45;
            this.btnAgregar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAgregar.CustomizableEdges = borderEdges3;
            this.btnAgregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAgregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAgregar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAgregar.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAgregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAgregar.IconMarginLeft = 11;
            this.btnAgregar.IconPadding = 10;
            this.btnAgregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAgregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAgregar.IconSize = 25;
            this.btnAgregar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAgregar.IdleBorderRadius = 1;
            this.btnAgregar.IdleBorderThickness = 1;
            this.btnAgregar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnAgregar.IdleIconLeftImage = null;
            this.btnAgregar.IdleIconRightImage = null;
            this.btnAgregar.IndicateFocus = false;
            this.btnAgregar.Location = new System.Drawing.Point(700, 176);
            this.btnAgregar.Name = "btnAgregar";
            this.btnAgregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregar.OnDisabledState.BorderRadius = 1;
            this.btnAgregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.OnDisabledState.BorderThickness = 1;
            this.btnAgregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregar.OnDisabledState.IconLeftImage = null;
            this.btnAgregar.OnDisabledState.IconRightImage = null;
            this.btnAgregar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgregar.onHoverState.BorderRadius = 1;
            this.btnAgregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.onHoverState.BorderThickness = 1;
            this.btnAgregar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.onHoverState.IconLeftImage = null;
            this.btnAgregar.onHoverState.IconRightImage = null;
            this.btnAgregar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAgregar.OnIdleState.BorderRadius = 1;
            this.btnAgregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.OnIdleState.BorderThickness = 1;
            this.btnAgregar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnAgregar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.OnIdleState.IconLeftImage = null;
            this.btnAgregar.OnIdleState.IconRightImage = null;
            this.btnAgregar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgregar.OnPressedState.BorderRadius = 1;
            this.btnAgregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAgregar.OnPressedState.BorderThickness = 1;
            this.btnAgregar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAgregar.OnPressedState.IconLeftImage = null;
            this.btnAgregar.OnPressedState.IconRightImage = null;
            this.btnAgregar.Size = new System.Drawing.Size(150, 39);
            this.btnAgregar.TabIndex = 16;
            this.btnAgregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAgregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAgregar.TextMarginLeft = 0;
            this.btnAgregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAgregar.UseDefaultRadiusAndThickness = true;
            this.btnAgregar.Click += new System.EventHandler(this.btnAgregar_Click);
            // 
            // TxtDni
            // 
            this.TxtDni.AcceptsReturn = false;
            this.TxtDni.AcceptsTab = false;
            this.TxtDni.AnimationSpeed = 200;
            this.TxtDni.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtDni.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtDni.BackColor = System.Drawing.Color.Transparent;
            this.TxtDni.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtDni.BackgroundImage")));
            this.TxtDni.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtDni.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtDni.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtDni.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtDni.BorderRadius = 1;
            this.TxtDni.BorderThickness = 1;
            this.TxtDni.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtDni.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtDni.DefaultText = "";
            this.TxtDni.FillColor = System.Drawing.Color.White;
            this.TxtDni.HideSelection = true;
            this.TxtDni.IconLeft = null;
            this.TxtDni.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.IconPadding = 10;
            this.TxtDni.IconRight = null;
            this.TxtDni.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.Lines = new string[0];
            this.TxtDni.Location = new System.Drawing.Point(27, 505);
            this.TxtDni.MaxLength = 32767;
            this.TxtDni.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtDni.Modified = false;
            this.TxtDni.Multiline = false;
            this.TxtDni.Name = "TxtDni";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtDni.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnIdleState = stateProperties4;
            this.TxtDni.Padding = new System.Windows.Forms.Padding(3);
            this.TxtDni.PasswordChar = '\0';
            this.TxtDni.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtDni.PlaceholderText = "DNI";
            this.TxtDni.ReadOnly = false;
            this.TxtDni.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtDni.SelectedText = "";
            this.TxtDni.SelectionLength = 0;
            this.TxtDni.SelectionStart = 0;
            this.TxtDni.ShortcutsEnabled = true;
            this.TxtDni.Size = new System.Drawing.Size(648, 37);
            this.TxtDni.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtDni.TabIndex = 14;
            this.TxtDni.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtDni.TextMarginBottom = 0;
            this.TxtDni.TextMarginLeft = 3;
            this.TxtDni.TextMarginTop = 0;
            this.TxtDni.TextPlaceholder = "DNI";
            this.TxtDni.UseSystemPasswordChar = false;
            this.TxtDni.WordWrap = true;
            // 
            // TxtApellido
            // 
            this.TxtApellido.AcceptsReturn = false;
            this.TxtApellido.AcceptsTab = false;
            this.TxtApellido.AnimationSpeed = 200;
            this.TxtApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtApellido.BackColor = System.Drawing.Color.Transparent;
            this.TxtApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtApellido.BackgroundImage")));
            this.TxtApellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtApellido.BorderRadius = 1;
            this.TxtApellido.BorderThickness = 1;
            this.TxtApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtApellido.DefaultText = "";
            this.TxtApellido.FillColor = System.Drawing.Color.White;
            this.TxtApellido.HideSelection = true;
            this.TxtApellido.IconLeft = null;
            this.TxtApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.IconPadding = 10;
            this.TxtApellido.IconRight = null;
            this.TxtApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.Lines = new string[0];
            this.TxtApellido.Location = new System.Drawing.Point(27, 591);
            this.TxtApellido.MaxLength = 32767;
            this.TxtApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtApellido.Modified = false;
            this.TxtApellido.Multiline = false;
            this.TxtApellido.Name = "TxtApellido";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtApellido.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnIdleState = stateProperties8;
            this.TxtApellido.Padding = new System.Windows.Forms.Padding(3);
            this.TxtApellido.PasswordChar = '\0';
            this.TxtApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtApellido.PlaceholderText = "Apellido";
            this.TxtApellido.ReadOnly = false;
            this.TxtApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtApellido.SelectedText = "";
            this.TxtApellido.SelectionLength = 0;
            this.TxtApellido.SelectionStart = 0;
            this.TxtApellido.ShortcutsEnabled = true;
            this.TxtApellido.Size = new System.Drawing.Size(648, 37);
            this.TxtApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtApellido.TabIndex = 13;
            this.TxtApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtApellido.TextMarginBottom = 0;
            this.TxtApellido.TextMarginLeft = 3;
            this.TxtApellido.TextMarginTop = 0;
            this.TxtApellido.TextPlaceholder = "Apellido";
            this.TxtApellido.UseSystemPasswordChar = false;
            this.TxtApellido.WordWrap = true;
            // 
            // TxtNombre
            // 
            this.TxtNombre.AcceptsReturn = false;
            this.TxtNombre.AcceptsTab = false;
            this.TxtNombre.AnimationSpeed = 200;
            this.TxtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtNombre.BackColor = System.Drawing.Color.Transparent;
            this.TxtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtNombre.BackgroundImage")));
            this.TxtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtNombre.BorderRadius = 1;
            this.TxtNombre.BorderThickness = 1;
            this.TxtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtNombre.DefaultText = "";
            this.TxtNombre.FillColor = System.Drawing.Color.White;
            this.TxtNombre.HideSelection = true;
            this.TxtNombre.IconLeft = null;
            this.TxtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.IconPadding = 10;
            this.TxtNombre.IconRight = null;
            this.TxtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.Lines = new string[0];
            this.TxtNombre.Location = new System.Drawing.Point(27, 548);
            this.TxtNombre.MaxLength = 32767;
            this.TxtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtNombre.Modified = false;
            this.TxtNombre.Multiline = false;
            this.TxtNombre.Name = "TxtNombre";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtNombre.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnIdleState = stateProperties12;
            this.TxtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.TxtNombre.PasswordChar = '\0';
            this.TxtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtNombre.PlaceholderText = "Nombre";
            this.TxtNombre.ReadOnly = false;
            this.TxtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtNombre.SelectedText = "";
            this.TxtNombre.SelectionLength = 0;
            this.TxtNombre.SelectionStart = 0;
            this.TxtNombre.ShortcutsEnabled = true;
            this.TxtNombre.Size = new System.Drawing.Size(648, 37);
            this.TxtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtNombre.TabIndex = 11;
            this.TxtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtNombre.TextMarginBottom = 0;
            this.TxtNombre.TextMarginLeft = 3;
            this.TxtNombre.TextMarginTop = 0;
            this.TxtNombre.TextPlaceholder = "Nombre";
            this.TxtNombre.UseSystemPasswordChar = false;
            this.TxtNombre.WordWrap = true;
            // 
            // lblNumeroUsuarios
            // 
            this.lblNumeroUsuarios.AutoSize = true;
            this.lblNumeroUsuarios.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNumeroUsuarios.ForeColor = System.Drawing.SystemColors.Control;
            this.lblNumeroUsuarios.Location = new System.Drawing.Point(24, 119);
            this.lblNumeroUsuarios.Name = "lblNumeroUsuarios";
            this.lblNumeroUsuarios.Size = new System.Drawing.Size(157, 18);
            this.lblNumeroUsuarios.TabIndex = 22;
            this.lblNumeroUsuarios.Text = "Numero de Usuarios:";
            // 
            // lblCantUser
            // 
            this.lblCantUser.AutoSize = true;
            this.lblCantUser.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCantUser.ForeColor = System.Drawing.SystemColors.Control;
            this.lblCantUser.Location = new System.Drawing.Point(187, 119);
            this.lblCantUser.Name = "lblCantUser";
            this.lblCantUser.Size = new System.Drawing.Size(80, 18);
            this.lblCantUser.TabIndex = 23;
            this.lblCantUser.Text = "xxxxxxxxx";
            // 
            // btnDesbloquear
            // 
            this.btnDesbloquear.AllowAnimations = true;
            this.btnDesbloquear.AllowMouseEffects = true;
            this.btnDesbloquear.AllowToggling = false;
            this.btnDesbloquear.AnimationSpeed = 200;
            this.btnDesbloquear.AutoGenerateColors = false;
            this.btnDesbloquear.AutoRoundBorders = false;
            this.btnDesbloquear.AutoSizeLeftIcon = true;
            this.btnDesbloquear.AutoSizeRightIcon = true;
            this.btnDesbloquear.BackColor = System.Drawing.Color.Transparent;
            this.btnDesbloquear.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDesbloquear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDesbloquear.BackgroundImage")));
            this.btnDesbloquear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDesbloquear.ButtonText = "Bloquear/Desbloquear";
            this.btnDesbloquear.ButtonTextMarginLeft = 0;
            this.btnDesbloquear.ColorContrastOnClick = 45;
            this.btnDesbloquear.ColorContrastOnHover = 45;
            this.btnDesbloquear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnDesbloquear.CustomizableEdges = borderEdges4;
            this.btnDesbloquear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDesbloquear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDesbloquear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDesbloquear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDesbloquear.Enabled = false;
            this.btnDesbloquear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDesbloquear.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnDesbloquear.ForeColor = System.Drawing.Color.White;
            this.btnDesbloquear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDesbloquear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDesbloquear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDesbloquear.IconMarginLeft = 11;
            this.btnDesbloquear.IconPadding = 10;
            this.btnDesbloquear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDesbloquear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDesbloquear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDesbloquear.IconSize = 25;
            this.btnDesbloquear.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDesbloquear.IdleBorderRadius = 1;
            this.btnDesbloquear.IdleBorderThickness = 1;
            this.btnDesbloquear.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDesbloquear.IdleIconLeftImage = null;
            this.btnDesbloquear.IdleIconRightImage = null;
            this.btnDesbloquear.IndicateFocus = false;
            this.btnDesbloquear.Location = new System.Drawing.Point(700, 296);
            this.btnDesbloquear.Name = "btnDesbloquear";
            this.btnDesbloquear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDesbloquear.OnDisabledState.BorderRadius = 1;
            this.btnDesbloquear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDesbloquear.OnDisabledState.BorderThickness = 1;
            this.btnDesbloquear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDesbloquear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDesbloquear.OnDisabledState.IconLeftImage = null;
            this.btnDesbloquear.OnDisabledState.IconRightImage = null;
            this.btnDesbloquear.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDesbloquear.onHoverState.BorderRadius = 1;
            this.btnDesbloquear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDesbloquear.onHoverState.BorderThickness = 1;
            this.btnDesbloquear.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDesbloquear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDesbloquear.onHoverState.IconLeftImage = null;
            this.btnDesbloquear.onHoverState.IconRightImage = null;
            this.btnDesbloquear.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDesbloquear.OnIdleState.BorderRadius = 1;
            this.btnDesbloquear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDesbloquear.OnIdleState.BorderThickness = 1;
            this.btnDesbloquear.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDesbloquear.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDesbloquear.OnIdleState.IconLeftImage = null;
            this.btnDesbloquear.OnIdleState.IconRightImage = null;
            this.btnDesbloquear.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDesbloquear.OnPressedState.BorderRadius = 1;
            this.btnDesbloquear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDesbloquear.OnPressedState.BorderThickness = 1;
            this.btnDesbloquear.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDesbloquear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDesbloquear.OnPressedState.IconLeftImage = null;
            this.btnDesbloquear.OnPressedState.IconRightImage = null;
            this.btnDesbloquear.Size = new System.Drawing.Size(150, 39);
            this.btnDesbloquear.TabIndex = 24;
            this.btnDesbloquear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDesbloquear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDesbloquear.TextMarginLeft = 0;
            this.btnDesbloquear.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDesbloquear.UseDefaultRadiusAndThickness = true;
            this.btnDesbloquear.Click += new System.EventHandler(this.btnDesbloquear_Click);
            // 
            // btnLimpiarSeleccion
            // 
            this.btnLimpiarSeleccion.AllowAnimations = true;
            this.btnLimpiarSeleccion.AllowMouseEffects = true;
            this.btnLimpiarSeleccion.AllowToggling = false;
            this.btnLimpiarSeleccion.AnimationSpeed = 200;
            this.btnLimpiarSeleccion.AutoGenerateColors = false;
            this.btnLimpiarSeleccion.AutoRoundBorders = false;
            this.btnLimpiarSeleccion.AutoSizeLeftIcon = true;
            this.btnLimpiarSeleccion.AutoSizeRightIcon = true;
            this.btnLimpiarSeleccion.BackColor = System.Drawing.Color.Transparent;
            this.btnLimpiarSeleccion.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLimpiarSeleccion.BackgroundImage")));
            this.btnLimpiarSeleccion.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.ButtonText = "Limpiar seleccion";
            this.btnLimpiarSeleccion.ButtonTextMarginLeft = 0;
            this.btnLimpiarSeleccion.ColorContrastOnClick = 45;
            this.btnLimpiarSeleccion.ColorContrastOnHover = 45;
            this.btnLimpiarSeleccion.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnLimpiarSeleccion.CustomizableEdges = borderEdges5;
            this.btnLimpiarSeleccion.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLimpiarSeleccion.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiarSeleccion.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLimpiarSeleccion.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLimpiarSeleccion.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLimpiarSeleccion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnLimpiarSeleccion.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLimpiarSeleccion.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiarSeleccion.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLimpiarSeleccion.IconMarginLeft = 11;
            this.btnLimpiarSeleccion.IconPadding = 10;
            this.btnLimpiarSeleccion.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLimpiarSeleccion.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiarSeleccion.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLimpiarSeleccion.IconSize = 25;
            this.btnLimpiarSeleccion.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.IdleBorderRadius = 1;
            this.btnLimpiarSeleccion.IdleBorderThickness = 1;
            this.btnLimpiarSeleccion.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.IdleIconLeftImage = null;
            this.btnLimpiarSeleccion.IdleIconRightImage = null;
            this.btnLimpiarSeleccion.IndicateFocus = false;
            this.btnLimpiarSeleccion.Location = new System.Drawing.Point(700, 548);
            this.btnLimpiarSeleccion.Name = "btnLimpiarSeleccion";
            this.btnLimpiarSeleccion.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiarSeleccion.OnDisabledState.BorderRadius = 1;
            this.btnLimpiarSeleccion.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.OnDisabledState.BorderThickness = 1;
            this.btnLimpiarSeleccion.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLimpiarSeleccion.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLimpiarSeleccion.OnDisabledState.IconLeftImage = null;
            this.btnLimpiarSeleccion.OnDisabledState.IconRightImage = null;
            this.btnLimpiarSeleccion.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLimpiarSeleccion.onHoverState.BorderRadius = 1;
            this.btnLimpiarSeleccion.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.onHoverState.BorderThickness = 1;
            this.btnLimpiarSeleccion.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLimpiarSeleccion.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.onHoverState.IconLeftImage = null;
            this.btnLimpiarSeleccion.onHoverState.IconRightImage = null;
            this.btnLimpiarSeleccion.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.OnIdleState.BorderRadius = 1;
            this.btnLimpiarSeleccion.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.OnIdleState.BorderThickness = 1;
            this.btnLimpiarSeleccion.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.OnIdleState.IconLeftImage = null;
            this.btnLimpiarSeleccion.OnIdleState.IconRightImage = null;
            this.btnLimpiarSeleccion.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLimpiarSeleccion.OnPressedState.BorderRadius = 1;
            this.btnLimpiarSeleccion.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.OnPressedState.BorderThickness = 1;
            this.btnLimpiarSeleccion.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLimpiarSeleccion.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.OnPressedState.IconLeftImage = null;
            this.btnLimpiarSeleccion.OnPressedState.IconRightImage = null;
            this.btnLimpiarSeleccion.Size = new System.Drawing.Size(150, 39);
            this.btnLimpiarSeleccion.TabIndex = 25;
            this.btnLimpiarSeleccion.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLimpiarSeleccion.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLimpiarSeleccion.TextMarginLeft = 0;
            this.btnLimpiarSeleccion.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLimpiarSeleccion.UseDefaultRadiusAndThickness = true;
            this.btnLimpiarSeleccion.Click += new System.EventHandler(this.btnLimpiar_Click);
            // 
            // btnInicio
            // 
            this.btnInicio.AllowAnimations = true;
            this.btnInicio.AllowMouseEffects = true;
            this.btnInicio.AllowToggling = false;
            this.btnInicio.AnimationSpeed = 200;
            this.btnInicio.AutoGenerateColors = false;
            this.btnInicio.AutoRoundBorders = false;
            this.btnInicio.AutoSizeLeftIcon = true;
            this.btnInicio.AutoSizeRightIcon = true;
            this.btnInicio.BackColor = System.Drawing.Color.Transparent;
            this.btnInicio.BackColor1 = System.Drawing.Color.Red;
            this.btnInicio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInicio.BackgroundImage")));
            this.btnInicio.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.ButtonText = "←";
            this.btnInicio.ButtonTextMarginLeft = 0;
            this.btnInicio.ColorContrastOnClick = 45;
            this.btnInicio.ColorContrastOnHover = 45;
            this.btnInicio.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnInicio.CustomizableEdges = borderEdges6;
            this.btnInicio.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInicio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInicio.Font = new System.Drawing.Font("Arial Black", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInicio.ForeColor = System.Drawing.Color.White;
            this.btnInicio.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInicio.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInicio.IconMarginLeft = 11;
            this.btnInicio.IconPadding = 10;
            this.btnInicio.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInicio.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInicio.IconSize = 25;
            this.btnInicio.IdleBorderColor = System.Drawing.Color.Red;
            this.btnInicio.IdleBorderRadius = 1;
            this.btnInicio.IdleBorderThickness = 1;
            this.btnInicio.IdleFillColor = System.Drawing.Color.Red;
            this.btnInicio.IdleIconLeftImage = null;
            this.btnInicio.IdleIconRightImage = null;
            this.btnInicio.IndicateFocus = false;
            this.btnInicio.Location = new System.Drawing.Point(869, 0);
            this.btnInicio.Name = "btnInicio";
            this.btnInicio.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.OnDisabledState.BorderRadius = 1;
            this.btnInicio.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnDisabledState.BorderThickness = 1;
            this.btnInicio.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.OnDisabledState.IconLeftImage = null;
            this.btnInicio.OnDisabledState.IconRightImage = null;
            this.btnInicio.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.onHoverState.BorderRadius = 1;
            this.btnInicio.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.onHoverState.BorderThickness = 1;
            this.btnInicio.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.onHoverState.IconLeftImage = null;
            this.btnInicio.onHoverState.IconRightImage = null;
            this.btnInicio.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnInicio.OnIdleState.BorderRadius = 1;
            this.btnInicio.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnIdleState.BorderThickness = 1;
            this.btnInicio.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnInicio.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.OnIdleState.IconLeftImage = null;
            this.btnInicio.OnIdleState.IconRightImage = null;
            this.btnInicio.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.OnPressedState.BorderRadius = 1;
            this.btnInicio.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnPressedState.BorderThickness = 1;
            this.btnInicio.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.OnPressedState.IconLeftImage = null;
            this.btnInicio.OnPressedState.IconRightImage = null;
            this.btnInicio.Size = new System.Drawing.Size(31, 26);
            this.btnInicio.TabIndex = 28;
            this.btnInicio.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnInicio.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInicio.TextMarginLeft = 0;
            this.btnInicio.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInicio.UseDefaultRadiusAndThickness = true;
            this.btnInicio.Click += new System.EventHandler(this.btnSalir_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox2);
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(198, 112);
            this.bunifuPanel1.TabIndex = 29;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(0, 0);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(198, 112);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 4;
            this.pictureBox2.TabStop = false;
            // 
            // cmbRoles
            // 
            this.cmbRoles.FormattingEnabled = true;
            this.cmbRoles.Location = new System.Drawing.Point(27, 634);
            this.cmbRoles.Name = "cmbRoles";
            this.cmbRoles.Size = new System.Drawing.Size(648, 21);
            this.cmbRoles.TabIndex = 30;
            this.cmbRoles.Text = "Rol";
            // 
            // FormGestionUsuario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(28)))), ((int)(((byte)(82)))));
            this.ClientSize = new System.Drawing.Size(900, 700);
            this.Controls.Add(this.cmbRoles);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.btnInicio);
            this.Controls.Add(this.btnLimpiarSeleccion);
            this.Controls.Add(this.btnDesbloquear);
            this.Controls.Add(this.lblCantUser);
            this.Controls.Add(this.lblNumeroUsuarios);
            this.Controls.Add(this.btnModificar);
            this.Controls.Add(this.btnEliminar);
            this.Controls.Add(this.btnAgregar);
            this.Controls.Add(this.TxtDni);
            this.Controls.Add(this.TxtApellido);
            this.Controls.Add(this.TxtNombre);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.DGusers);
            this.Name = "FormGestionUsuario";
            this.Text = "FormGestionUsuario";
            ((System.ComponentModel.ISupportInitialize)(this.DGusers)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView DGusers;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModificar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEliminar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAgregar;
        private Bunifu.UI.WinForms.BunifuTextBox TxtDni;
        private Bunifu.UI.WinForms.BunifuTextBox TxtApellido;
        private Bunifu.UI.WinForms.BunifuTextBox TxtNombre;
        private System.Windows.Forms.Label lblNumeroUsuarios;
        private System.Windows.Forms.Label lblCantUser;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDesbloquear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLimpiarSeleccion;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInicio;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.ComboBox cmbRoles;
    }
}