namespace GUI
{
    partial class FormMaestroClientes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMaestroClientes));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.lblPrincipalGestionClientes = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.btnInicio = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLimpiarSeleccion = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblCantClientes = new System.Windows.Forms.Label();
            this.lblNumeroClientes = new System.Windows.Forms.Label();
            this.btnModificar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtMail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtDni = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.DG_Clientes = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnChangeEncrypt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDeserializar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSerializar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DG_Clientes)).BeginInit();
            this.SuspendLayout();
            // 
            // lblPrincipalGestionClientes
            // 
            this.lblPrincipalGestionClientes.AllowParentOverrides = false;
            this.lblPrincipalGestionClientes.AutoEllipsis = false;
            this.lblPrincipalGestionClientes.AutoSize = false;
            this.lblPrincipalGestionClientes.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblPrincipalGestionClientes.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblPrincipalGestionClientes.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblPrincipalGestionClientes.Font = new System.Drawing.Font("Arial Rounded MT Bold", 20.25F, System.Drawing.FontStyle.Bold);
            this.lblPrincipalGestionClientes.ForeColor = System.Drawing.SystemColors.Control;
            this.lblPrincipalGestionClientes.Location = new System.Drawing.Point(0, 0);
            this.lblPrincipalGestionClientes.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.lblPrincipalGestionClientes.Name = "lblPrincipalGestionClientes";
            this.lblPrincipalGestionClientes.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPrincipalGestionClientes.Size = new System.Drawing.Size(1200, 138);
            this.lblPrincipalGestionClientes.TabIndex = 16;
            this.lblPrincipalGestionClientes.Text = "Gestion Clientes";
            this.lblPrincipalGestionClientes.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblPrincipalGestionClientes.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox2);
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(264, 138);
            this.bunifuPanel1.TabIndex = 17;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(0, 0);
            this.pictureBox2.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(264, 138);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 6;
            this.pictureBox2.TabStop = false;
            // 
            // btnInicio
            // 
            this.btnInicio.AllowAnimations = true;
            this.btnInicio.AllowMouseEffects = true;
            this.btnInicio.AllowToggling = false;
            this.btnInicio.AnimationSpeed = 200;
            this.btnInicio.AutoGenerateColors = false;
            this.btnInicio.AutoRoundBorders = false;
            this.btnInicio.AutoSizeLeftIcon = true;
            this.btnInicio.AutoSizeRightIcon = true;
            this.btnInicio.BackColor = System.Drawing.Color.Transparent;
            this.btnInicio.BackColor1 = System.Drawing.Color.Red;
            this.btnInicio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInicio.BackgroundImage")));
            this.btnInicio.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.ButtonText = "←";
            this.btnInicio.ButtonTextMarginLeft = 0;
            this.btnInicio.ColorContrastOnClick = 45;
            this.btnInicio.ColorContrastOnHover = 45;
            this.btnInicio.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnInicio.CustomizableEdges = borderEdges1;
            this.btnInicio.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInicio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInicio.Font = new System.Drawing.Font("Arial Black", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInicio.ForeColor = System.Drawing.Color.White;
            this.btnInicio.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInicio.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnInicio.IconMarginLeft = 11;
            this.btnInicio.IconPadding = 10;
            this.btnInicio.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInicio.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInicio.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInicio.IconSize = 25;
            this.btnInicio.IdleBorderColor = System.Drawing.Color.Red;
            this.btnInicio.IdleBorderRadius = 1;
            this.btnInicio.IdleBorderThickness = 1;
            this.btnInicio.IdleFillColor = System.Drawing.Color.Red;
            this.btnInicio.IdleIconLeftImage = null;
            this.btnInicio.IdleIconRightImage = null;
            this.btnInicio.IndicateFocus = false;
            this.btnInicio.Location = new System.Drawing.Point(1159, 0);
            this.btnInicio.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnInicio.Name = "btnInicio";
            this.btnInicio.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInicio.OnDisabledState.BorderRadius = 1;
            this.btnInicio.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnDisabledState.BorderThickness = 1;
            this.btnInicio.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInicio.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInicio.OnDisabledState.IconLeftImage = null;
            this.btnInicio.OnDisabledState.IconRightImage = null;
            this.btnInicio.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.onHoverState.BorderRadius = 1;
            this.btnInicio.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.onHoverState.BorderThickness = 1;
            this.btnInicio.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.onHoverState.IconLeftImage = null;
            this.btnInicio.onHoverState.IconRightImage = null;
            this.btnInicio.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnInicio.OnIdleState.BorderRadius = 1;
            this.btnInicio.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnIdleState.BorderThickness = 1;
            this.btnInicio.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnInicio.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.OnIdleState.IconLeftImage = null;
            this.btnInicio.OnIdleState.IconRightImage = null;
            this.btnInicio.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.OnPressedState.BorderRadius = 1;
            this.btnInicio.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInicio.OnPressedState.BorderThickness = 1;
            this.btnInicio.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnInicio.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnInicio.OnPressedState.IconLeftImage = null;
            this.btnInicio.OnPressedState.IconRightImage = null;
            this.btnInicio.Size = new System.Drawing.Size(41, 32);
            this.btnInicio.TabIndex = 59;
            this.btnInicio.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnInicio.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInicio.TextMarginLeft = 0;
            this.btnInicio.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnInicio.UseDefaultRadiusAndThickness = true;
            this.btnInicio.Click += new System.EventHandler(this.btnInicio_Click);
            // 
            // btnLimpiarSeleccion
            // 
            this.btnLimpiarSeleccion.AllowAnimations = true;
            this.btnLimpiarSeleccion.AllowMouseEffects = true;
            this.btnLimpiarSeleccion.AllowToggling = false;
            this.btnLimpiarSeleccion.AnimationSpeed = 200;
            this.btnLimpiarSeleccion.AutoGenerateColors = false;
            this.btnLimpiarSeleccion.AutoRoundBorders = false;
            this.btnLimpiarSeleccion.AutoSizeLeftIcon = true;
            this.btnLimpiarSeleccion.AutoSizeRightIcon = true;
            this.btnLimpiarSeleccion.BackColor = System.Drawing.Color.Transparent;
            this.btnLimpiarSeleccion.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLimpiarSeleccion.BackgroundImage")));
            this.btnLimpiarSeleccion.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.ButtonText = "Limpiar seleccion";
            this.btnLimpiarSeleccion.ButtonTextMarginLeft = 0;
            this.btnLimpiarSeleccion.ColorContrastOnClick = 45;
            this.btnLimpiarSeleccion.ColorContrastOnHover = 45;
            this.btnLimpiarSeleccion.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnLimpiarSeleccion.CustomizableEdges = borderEdges2;
            this.btnLimpiarSeleccion.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLimpiarSeleccion.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiarSeleccion.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLimpiarSeleccion.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLimpiarSeleccion.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLimpiarSeleccion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnLimpiarSeleccion.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLimpiarSeleccion.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiarSeleccion.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLimpiarSeleccion.IconMarginLeft = 11;
            this.btnLimpiarSeleccion.IconPadding = 10;
            this.btnLimpiarSeleccion.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLimpiarSeleccion.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiarSeleccion.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLimpiarSeleccion.IconSize = 25;
            this.btnLimpiarSeleccion.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.IdleBorderRadius = 1;
            this.btnLimpiarSeleccion.IdleBorderThickness = 1;
            this.btnLimpiarSeleccion.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.IdleIconLeftImage = null;
            this.btnLimpiarSeleccion.IdleIconRightImage = null;
            this.btnLimpiarSeleccion.IndicateFocus = false;
            this.btnLimpiarSeleccion.Location = new System.Drawing.Point(945, 692);
            this.btnLimpiarSeleccion.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnLimpiarSeleccion.Name = "btnLimpiarSeleccion";
            this.btnLimpiarSeleccion.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiarSeleccion.OnDisabledState.BorderRadius = 1;
            this.btnLimpiarSeleccion.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.OnDisabledState.BorderThickness = 1;
            this.btnLimpiarSeleccion.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLimpiarSeleccion.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLimpiarSeleccion.OnDisabledState.IconLeftImage = null;
            this.btnLimpiarSeleccion.OnDisabledState.IconRightImage = null;
            this.btnLimpiarSeleccion.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLimpiarSeleccion.onHoverState.BorderRadius = 1;
            this.btnLimpiarSeleccion.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.onHoverState.BorderThickness = 1;
            this.btnLimpiarSeleccion.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLimpiarSeleccion.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.onHoverState.IconLeftImage = null;
            this.btnLimpiarSeleccion.onHoverState.IconRightImage = null;
            this.btnLimpiarSeleccion.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.OnIdleState.BorderRadius = 1;
            this.btnLimpiarSeleccion.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.OnIdleState.BorderThickness = 1;
            this.btnLimpiarSeleccion.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnLimpiarSeleccion.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.OnIdleState.IconLeftImage = null;
            this.btnLimpiarSeleccion.OnIdleState.IconRightImage = null;
            this.btnLimpiarSeleccion.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLimpiarSeleccion.OnPressedState.BorderRadius = 1;
            this.btnLimpiarSeleccion.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiarSeleccion.OnPressedState.BorderThickness = 1;
            this.btnLimpiarSeleccion.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLimpiarSeleccion.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiarSeleccion.OnPressedState.IconLeftImage = null;
            this.btnLimpiarSeleccion.OnPressedState.IconRightImage = null;
            this.btnLimpiarSeleccion.Size = new System.Drawing.Size(200, 48);
            this.btnLimpiarSeleccion.TabIndex = 71;
            this.btnLimpiarSeleccion.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLimpiarSeleccion.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLimpiarSeleccion.TextMarginLeft = 0;
            this.btnLimpiarSeleccion.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLimpiarSeleccion.UseDefaultRadiusAndThickness = true;
            this.btnLimpiarSeleccion.Click += new System.EventHandler(this.btnLimpiar_Click);
            // 
            // lblCantClientes
            // 
            this.lblCantClientes.AutoSize = true;
            this.lblCantClientes.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCantClientes.ForeColor = System.Drawing.SystemColors.Control;
            this.lblCantClientes.Location = new System.Drawing.Point(261, 181);
            this.lblCantClientes.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCantClientes.Name = "lblCantClientes";
            this.lblCantClientes.Size = new System.Drawing.Size(109, 22);
            this.lblCantClientes.TabIndex = 69;
            this.lblCantClientes.Text = "xxxxxxxxx";
            // 
            // lblNumeroClientes
            // 
            this.lblNumeroClientes.AutoSize = true;
            this.lblNumeroClientes.Font = new System.Drawing.Font("Arial", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNumeroClientes.ForeColor = System.Drawing.SystemColors.Control;
            this.lblNumeroClientes.Location = new System.Drawing.Point(44, 181);
            this.lblNumeroClientes.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblNumeroClientes.Name = "lblNumeroClientes";
            this.lblNumeroClientes.Size = new System.Drawing.Size(198, 22);
            this.lblNumeroClientes.TabIndex = 68;
            this.lblNumeroClientes.Text = "Numero de Clientes:";
            // 
            // btnModificar
            // 
            this.btnModificar.AllowAnimations = true;
            this.btnModificar.AllowMouseEffects = true;
            this.btnModificar.AllowToggling = false;
            this.btnModificar.AnimationSpeed = 200;
            this.btnModificar.AutoGenerateColors = false;
            this.btnModificar.AutoRoundBorders = false;
            this.btnModificar.AutoSizeLeftIcon = true;
            this.btnModificar.AutoSizeRightIcon = true;
            this.btnModificar.BackColor = System.Drawing.Color.Transparent;
            this.btnModificar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnModificar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModificar.BackgroundImage")));
            this.btnModificar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.ButtonText = "Modificar";
            this.btnModificar.ButtonTextMarginLeft = 0;
            this.btnModificar.ColorContrastOnClick = 45;
            this.btnModificar.ColorContrastOnHover = 45;
            this.btnModificar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnModificar.CustomizableEdges = borderEdges3;
            this.btnModificar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModificar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModificar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnModificar.ForeColor = System.Drawing.Color.White;
            this.btnModificar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModificar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModificar.IconMarginLeft = 11;
            this.btnModificar.IconPadding = 10;
            this.btnModificar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModificar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModificar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModificar.IconSize = 25;
            this.btnModificar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.IdleBorderRadius = 1;
            this.btnModificar.IdleBorderThickness = 1;
            this.btnModificar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.IdleIconLeftImage = null;
            this.btnModificar.IdleIconRightImage = null;
            this.btnModificar.IndicateFocus = false;
            this.btnModificar.Location = new System.Drawing.Point(945, 623);
            this.btnModificar.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnModificar.Name = "btnModificar";
            this.btnModificar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModificar.OnDisabledState.BorderRadius = 1;
            this.btnModificar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnDisabledState.BorderThickness = 1;
            this.btnModificar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModificar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModificar.OnDisabledState.IconLeftImage = null;
            this.btnModificar.OnDisabledState.IconRightImage = null;
            this.btnModificar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificar.onHoverState.BorderRadius = 1;
            this.btnModificar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.onHoverState.BorderThickness = 1;
            this.btnModificar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModificar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModificar.onHoverState.IconLeftImage = null;
            this.btnModificar.onHoverState.IconRightImage = null;
            this.btnModificar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.OnIdleState.BorderRadius = 1;
            this.btnModificar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnIdleState.BorderThickness = 1;
            this.btnModificar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnModificar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnModificar.OnIdleState.IconLeftImage = null;
            this.btnModificar.OnIdleState.IconRightImage = null;
            this.btnModificar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificar.OnPressedState.BorderRadius = 1;
            this.btnModificar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModificar.OnPressedState.BorderThickness = 1;
            this.btnModificar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModificar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModificar.OnPressedState.IconLeftImage = null;
            this.btnModificar.OnPressedState.IconRightImage = null;
            this.btnModificar.Size = new System.Drawing.Size(200, 48);
            this.btnModificar.TabIndex = 67;
            this.btnModificar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModificar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModificar.TextMarginLeft = 0;
            this.btnModificar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModificar.UseDefaultRadiusAndThickness = true;
            this.btnModificar.Click += new System.EventHandler(this.btnModificar_Click);
            // 
            // txtMail
            // 
            this.txtMail.AcceptsReturn = false;
            this.txtMail.AcceptsTab = false;
            this.txtMail.AnimationSpeed = 200;
            this.txtMail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMail.BackColor = System.Drawing.Color.Transparent;
            this.txtMail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMail.BackgroundImage")));
            this.txtMail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMail.BorderRadius = 1;
            this.txtMail.BorderThickness = 1;
            this.txtMail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMail.DefaultText = "";
            this.txtMail.FillColor = System.Drawing.Color.White;
            this.txtMail.HideSelection = true;
            this.txtMail.IconLeft = null;
            this.txtMail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMail.IconPadding = 10;
            this.txtMail.IconRight = null;
            this.txtMail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMail.Lines = new string[0];
            this.txtMail.Location = new System.Drawing.Point(48, 769);
            this.txtMail.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtMail.MaxLength = 32767;
            this.txtMail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMail.Modified = false;
            this.txtMail.Multiline = false;
            this.txtMail.Name = "txtMail";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMail.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMail.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMail.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMail.OnIdleState = stateProperties4;
            this.txtMail.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtMail.PasswordChar = '\0';
            this.txtMail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMail.PlaceholderText = "Correo";
            this.txtMail.ReadOnly = false;
            this.txtMail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMail.SelectedText = "";
            this.txtMail.SelectionLength = 0;
            this.txtMail.SelectionStart = 0;
            this.txtMail.ShortcutsEnabled = true;
            this.txtMail.Size = new System.Drawing.Size(864, 46);
            this.txtMail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMail.TabIndex = 64;
            this.txtMail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMail.TextMarginBottom = 0;
            this.txtMail.TextMarginLeft = 3;
            this.txtMail.TextMarginTop = 0;
            this.txtMail.TextPlaceholder = "Correo";
            this.txtMail.UseSystemPasswordChar = false;
            this.txtMail.WordWrap = true;
            // 
            // TxtDni
            // 
            this.TxtDni.AcceptsReturn = false;
            this.TxtDni.AcceptsTab = false;
            this.TxtDni.AnimationSpeed = 200;
            this.TxtDni.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtDni.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtDni.BackColor = System.Drawing.Color.Transparent;
            this.TxtDni.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtDni.BackgroundImage")));
            this.TxtDni.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtDni.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtDni.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtDni.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtDni.BorderRadius = 1;
            this.TxtDni.BorderThickness = 1;
            this.TxtDni.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtDni.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtDni.DefaultText = "";
            this.TxtDni.FillColor = System.Drawing.Color.White;
            this.TxtDni.HideSelection = true;
            this.TxtDni.IconLeft = null;
            this.TxtDni.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.IconPadding = 10;
            this.TxtDni.IconRight = null;
            this.TxtDni.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDni.Lines = new string[0];
            this.TxtDni.Location = new System.Drawing.Point(48, 610);
            this.TxtDni.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TxtDni.MaxLength = 32767;
            this.TxtDni.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtDni.Modified = false;
            this.TxtDni.Multiline = false;
            this.TxtDni.Name = "TxtDni";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtDni.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtDni.OnIdleState = stateProperties8;
            this.TxtDni.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TxtDni.PasswordChar = '\0';
            this.TxtDni.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtDni.PlaceholderText = "DNI";
            this.TxtDni.ReadOnly = false;
            this.TxtDni.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtDni.SelectedText = "";
            this.TxtDni.SelectionLength = 0;
            this.TxtDni.SelectionStart = 0;
            this.TxtDni.ShortcutsEnabled = true;
            this.TxtDni.Size = new System.Drawing.Size(864, 46);
            this.TxtDni.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtDni.TabIndex = 63;
            this.TxtDni.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtDni.TextMarginBottom = 0;
            this.TxtDni.TextMarginLeft = 3;
            this.TxtDni.TextMarginTop = 0;
            this.TxtDni.TextPlaceholder = "DNI";
            this.TxtDni.UseSystemPasswordChar = false;
            this.TxtDni.WordWrap = true;
            // 
            // TxtApellido
            // 
            this.TxtApellido.AcceptsReturn = false;
            this.TxtApellido.AcceptsTab = false;
            this.TxtApellido.AnimationSpeed = 200;
            this.TxtApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtApellido.BackColor = System.Drawing.Color.Transparent;
            this.TxtApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtApellido.BackgroundImage")));
            this.TxtApellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtApellido.BorderRadius = 1;
            this.TxtApellido.BorderThickness = 1;
            this.TxtApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtApellido.DefaultText = "";
            this.TxtApellido.FillColor = System.Drawing.Color.White;
            this.TxtApellido.HideSelection = true;
            this.TxtApellido.IconLeft = null;
            this.TxtApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.IconPadding = 10;
            this.TxtApellido.IconRight = null;
            this.TxtApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtApellido.Lines = new string[0];
            this.TxtApellido.Location = new System.Drawing.Point(48, 716);
            this.TxtApellido.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TxtApellido.MaxLength = 32767;
            this.TxtApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtApellido.Modified = false;
            this.TxtApellido.Multiline = false;
            this.TxtApellido.Name = "TxtApellido";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtApellido.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtApellido.OnIdleState = stateProperties12;
            this.TxtApellido.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TxtApellido.PasswordChar = '\0';
            this.TxtApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtApellido.PlaceholderText = "Apellido";
            this.TxtApellido.ReadOnly = false;
            this.TxtApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtApellido.SelectedText = "";
            this.TxtApellido.SelectionLength = 0;
            this.TxtApellido.SelectionStart = 0;
            this.TxtApellido.ShortcutsEnabled = true;
            this.TxtApellido.Size = new System.Drawing.Size(864, 46);
            this.TxtApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtApellido.TabIndex = 62;
            this.TxtApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtApellido.TextMarginBottom = 0;
            this.TxtApellido.TextMarginLeft = 3;
            this.TxtApellido.TextMarginTop = 0;
            this.TxtApellido.TextPlaceholder = "Apellido";
            this.TxtApellido.UseSystemPasswordChar = false;
            this.TxtApellido.WordWrap = true;
            // 
            // TxtNombre
            // 
            this.TxtNombre.AcceptsReturn = false;
            this.TxtNombre.AcceptsTab = false;
            this.TxtNombre.AnimationSpeed = 200;
            this.TxtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtNombre.BackColor = System.Drawing.Color.Transparent;
            this.TxtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtNombre.BackgroundImage")));
            this.TxtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TxtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TxtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtNombre.BorderRadius = 1;
            this.TxtNombre.BorderThickness = 1;
            this.TxtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TxtNombre.DefaultText = "";
            this.TxtNombre.FillColor = System.Drawing.Color.White;
            this.TxtNombre.HideSelection = true;
            this.TxtNombre.IconLeft = null;
            this.TxtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.IconPadding = 10;
            this.TxtNombre.IconRight = null;
            this.TxtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtNombre.Lines = new string[0];
            this.TxtNombre.Location = new System.Drawing.Point(48, 663);
            this.TxtNombre.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TxtNombre.MaxLength = 32767;
            this.TxtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtNombre.Modified = false;
            this.TxtNombre.Multiline = false;
            this.TxtNombre.Name = "TxtNombre";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtNombre.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TxtNombre.OnIdleState = stateProperties16;
            this.TxtNombre.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TxtNombre.PasswordChar = '\0';
            this.TxtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtNombre.PlaceholderText = "Nombre";
            this.TxtNombre.ReadOnly = false;
            this.TxtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtNombre.SelectedText = "";
            this.TxtNombre.SelectionLength = 0;
            this.TxtNombre.SelectionStart = 0;
            this.TxtNombre.ShortcutsEnabled = true;
            this.TxtNombre.Size = new System.Drawing.Size(864, 46);
            this.TxtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtNombre.TabIndex = 61;
            this.TxtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtNombre.TextMarginBottom = 0;
            this.TxtNombre.TextMarginLeft = 3;
            this.TxtNombre.TextMarginTop = 0;
            this.TxtNombre.TextPlaceholder = "Nombre";
            this.TxtNombre.UseSystemPasswordChar = false;
            this.TxtNombre.WordWrap = true;
            // 
            // DG_Clientes
            // 
            this.DG_Clientes.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.DG_Clientes.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.DG_Clientes.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.DG_Clientes.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DG_Clientes.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.DG_Clientes.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.DG_Clientes.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DG_Clientes.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.DG_Clientes.ColumnHeadersHeight = 40;
            this.DG_Clientes.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.DG_Clientes.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DG_Clientes.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DG_Clientes.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DG_Clientes.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.DG_Clientes.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.DG_Clientes.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DG_Clientes.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.DG_Clientes.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.DG_Clientes.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.DG_Clientes.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.DG_Clientes.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.DG_Clientes.CurrentTheme.Name = null;
            this.DG_Clientes.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.DG_Clientes.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DG_Clientes.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DG_Clientes.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.DG_Clientes.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.DG_Clientes.DefaultCellStyle = dataGridViewCellStyle3;
            this.DG_Clientes.EnableHeadersVisualStyles = false;
            this.DG_Clientes.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.DG_Clientes.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.DG_Clientes.HeaderBgColor = System.Drawing.Color.Empty;
            this.DG_Clientes.HeaderForeColor = System.Drawing.Color.White;
            this.DG_Clientes.Location = new System.Drawing.Point(48, 207);
            this.DG_Clientes.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.DG_Clientes.MultiSelect = false;
            this.DG_Clientes.Name = "DG_Clientes";
            this.DG_Clientes.ReadOnly = true;
            this.DG_Clientes.RowHeadersVisible = false;
            this.DG_Clientes.RowHeadersWidth = 51;
            this.DG_Clientes.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.DG_Clientes.RowTemplate.Height = 40;
            this.DG_Clientes.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DG_Clientes.Size = new System.Drawing.Size(1097, 382);
            this.DG_Clientes.TabIndex = 60;
            this.DG_Clientes.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.DG_Clientes.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.DG_Clientes_CellContentClick);
            // 
            // btnChangeEncrypt
            // 
            this.btnChangeEncrypt.AllowAnimations = true;
            this.btnChangeEncrypt.AllowMouseEffects = true;
            this.btnChangeEncrypt.AllowToggling = false;
            this.btnChangeEncrypt.AnimationSpeed = 200;
            this.btnChangeEncrypt.AutoGenerateColors = false;
            this.btnChangeEncrypt.AutoRoundBorders = false;
            this.btnChangeEncrypt.AutoSizeLeftIcon = true;
            this.btnChangeEncrypt.AutoSizeRightIcon = true;
            this.btnChangeEncrypt.BackColor = System.Drawing.Color.Transparent;
            this.btnChangeEncrypt.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnChangeEncrypt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangeEncrypt.BackgroundImage")));
            this.btnChangeEncrypt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeEncrypt.ButtonText = "Activar/Desactivar encriptacion";
            this.btnChangeEncrypt.ButtonTextMarginLeft = 0;
            this.btnChangeEncrypt.ColorContrastOnClick = 45;
            this.btnChangeEncrypt.ColorContrastOnHover = 45;
            this.btnChangeEncrypt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnChangeEncrypt.CustomizableEdges = borderEdges4;
            this.btnChangeEncrypt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangeEncrypt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangeEncrypt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangeEncrypt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangeEncrypt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangeEncrypt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnChangeEncrypt.ForeColor = System.Drawing.Color.White;
            this.btnChangeEncrypt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangeEncrypt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeEncrypt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChangeEncrypt.IconMarginLeft = 11;
            this.btnChangeEncrypt.IconPadding = 10;
            this.btnChangeEncrypt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangeEncrypt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeEncrypt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChangeEncrypt.IconSize = 25;
            this.btnChangeEncrypt.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChangeEncrypt.IdleBorderRadius = 1;
            this.btnChangeEncrypt.IdleBorderThickness = 1;
            this.btnChangeEncrypt.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnChangeEncrypt.IdleIconLeftImage = null;
            this.btnChangeEncrypt.IdleIconRightImage = null;
            this.btnChangeEncrypt.IndicateFocus = false;
            this.btnChangeEncrypt.Location = new System.Drawing.Point(859, 166);
            this.btnChangeEncrypt.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnChangeEncrypt.Name = "btnChangeEncrypt";
            this.btnChangeEncrypt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangeEncrypt.OnDisabledState.BorderRadius = 1;
            this.btnChangeEncrypt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeEncrypt.OnDisabledState.BorderThickness = 1;
            this.btnChangeEncrypt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangeEncrypt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangeEncrypt.OnDisabledState.IconLeftImage = null;
            this.btnChangeEncrypt.OnDisabledState.IconRightImage = null;
            this.btnChangeEncrypt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangeEncrypt.onHoverState.BorderRadius = 1;
            this.btnChangeEncrypt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeEncrypt.onHoverState.BorderThickness = 1;
            this.btnChangeEncrypt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangeEncrypt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChangeEncrypt.onHoverState.IconLeftImage = null;
            this.btnChangeEncrypt.onHoverState.IconRightImage = null;
            this.btnChangeEncrypt.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChangeEncrypt.OnIdleState.BorderRadius = 1;
            this.btnChangeEncrypt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeEncrypt.OnIdleState.BorderThickness = 1;
            this.btnChangeEncrypt.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnChangeEncrypt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChangeEncrypt.OnIdleState.IconLeftImage = null;
            this.btnChangeEncrypt.OnIdleState.IconRightImage = null;
            this.btnChangeEncrypt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangeEncrypt.OnPressedState.BorderRadius = 1;
            this.btnChangeEncrypt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeEncrypt.OnPressedState.BorderThickness = 1;
            this.btnChangeEncrypt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangeEncrypt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangeEncrypt.OnPressedState.IconLeftImage = null;
            this.btnChangeEncrypt.OnPressedState.IconRightImage = null;
            this.btnChangeEncrypt.Size = new System.Drawing.Size(287, 37);
            this.btnChangeEncrypt.TabIndex = 72;
            this.btnChangeEncrypt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangeEncrypt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangeEncrypt.TextMarginLeft = 0;
            this.btnChangeEncrypt.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangeEncrypt.UseDefaultRadiusAndThickness = true;
            this.btnChangeEncrypt.Click += new System.EventHandler(this.btnChangeEncrypt_Click);
            // 
            // btnDeserializar
            // 
            this.btnDeserializar.AllowAnimations = true;
            this.btnDeserializar.AllowMouseEffects = true;
            this.btnDeserializar.AllowToggling = false;
            this.btnDeserializar.AnimationSpeed = 200;
            this.btnDeserializar.AutoGenerateColors = false;
            this.btnDeserializar.AutoRoundBorders = false;
            this.btnDeserializar.AutoSizeLeftIcon = true;
            this.btnDeserializar.AutoSizeRightIcon = true;
            this.btnDeserializar.BackColor = System.Drawing.Color.Transparent;
            this.btnDeserializar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDeserializar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDeserializar.BackgroundImage")));
            this.btnDeserializar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeserializar.ButtonText = "Deserializar";
            this.btnDeserializar.ButtonTextMarginLeft = 0;
            this.btnDeserializar.ColorContrastOnClick = 45;
            this.btnDeserializar.ColorContrastOnHover = 45;
            this.btnDeserializar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnDeserializar.CustomizableEdges = borderEdges5;
            this.btnDeserializar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDeserializar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeserializar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeserializar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeserializar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDeserializar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnDeserializar.ForeColor = System.Drawing.Color.White;
            this.btnDeserializar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDeserializar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDeserializar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDeserializar.IconMarginLeft = 11;
            this.btnDeserializar.IconPadding = 10;
            this.btnDeserializar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDeserializar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDeserializar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDeserializar.IconSize = 25;
            this.btnDeserializar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDeserializar.IdleBorderRadius = 1;
            this.btnDeserializar.IdleBorderThickness = 1;
            this.btnDeserializar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDeserializar.IdleIconLeftImage = null;
            this.btnDeserializar.IdleIconRightImage = null;
            this.btnDeserializar.IndicateFocus = false;
            this.btnDeserializar.Location = new System.Drawing.Point(584, 162);
            this.btnDeserializar.Margin = new System.Windows.Forms.Padding(4);
            this.btnDeserializar.Name = "btnDeserializar";
            this.btnDeserializar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeserializar.OnDisabledState.BorderRadius = 1;
            this.btnDeserializar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeserializar.OnDisabledState.BorderThickness = 1;
            this.btnDeserializar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeserializar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeserializar.OnDisabledState.IconLeftImage = null;
            this.btnDeserializar.OnDisabledState.IconRightImage = null;
            this.btnDeserializar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDeserializar.onHoverState.BorderRadius = 1;
            this.btnDeserializar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeserializar.onHoverState.BorderThickness = 1;
            this.btnDeserializar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDeserializar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDeserializar.onHoverState.IconLeftImage = null;
            this.btnDeserializar.onHoverState.IconRightImage = null;
            this.btnDeserializar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDeserializar.OnIdleState.BorderRadius = 1;
            this.btnDeserializar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeserializar.OnIdleState.BorderThickness = 1;
            this.btnDeserializar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDeserializar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDeserializar.OnIdleState.IconLeftImage = null;
            this.btnDeserializar.OnIdleState.IconRightImage = null;
            this.btnDeserializar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDeserializar.OnPressedState.BorderRadius = 1;
            this.btnDeserializar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeserializar.OnPressedState.BorderThickness = 1;
            this.btnDeserializar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDeserializar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDeserializar.OnPressedState.IconLeftImage = null;
            this.btnDeserializar.OnPressedState.IconRightImage = null;
            this.btnDeserializar.Size = new System.Drawing.Size(153, 37);
            this.btnDeserializar.TabIndex = 73;
            this.btnDeserializar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDeserializar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDeserializar.TextMarginLeft = 0;
            this.btnDeserializar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDeserializar.UseDefaultRadiusAndThickness = true;
            this.btnDeserializar.Click += new System.EventHandler(this.btnDeserializar_Click);
            // 
            // btnSerializar
            // 
            this.btnSerializar.AllowAnimations = true;
            this.btnSerializar.AllowMouseEffects = true;
            this.btnSerializar.AllowToggling = false;
            this.btnSerializar.AnimationSpeed = 200;
            this.btnSerializar.AutoGenerateColors = false;
            this.btnSerializar.AutoRoundBorders = false;
            this.btnSerializar.AutoSizeLeftIcon = true;
            this.btnSerializar.AutoSizeRightIcon = true;
            this.btnSerializar.BackColor = System.Drawing.Color.Transparent;
            this.btnSerializar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSerializar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSerializar.BackgroundImage")));
            this.btnSerializar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSerializar.ButtonText = "Serializar";
            this.btnSerializar.ButtonTextMarginLeft = 0;
            this.btnSerializar.ColorContrastOnClick = 45;
            this.btnSerializar.ColorContrastOnHover = 45;
            this.btnSerializar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnSerializar.CustomizableEdges = borderEdges6;
            this.btnSerializar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSerializar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSerializar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSerializar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSerializar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSerializar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSerializar.ForeColor = System.Drawing.Color.White;
            this.btnSerializar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSerializar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSerializar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSerializar.IconMarginLeft = 11;
            this.btnSerializar.IconPadding = 10;
            this.btnSerializar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSerializar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSerializar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSerializar.IconSize = 25;
            this.btnSerializar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSerializar.IdleBorderRadius = 1;
            this.btnSerializar.IdleBorderThickness = 1;
            this.btnSerializar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSerializar.IdleIconLeftImage = null;
            this.btnSerializar.IdleIconRightImage = null;
            this.btnSerializar.IndicateFocus = false;
            this.btnSerializar.Location = new System.Drawing.Point(409, 162);
            this.btnSerializar.Margin = new System.Windows.Forms.Padding(4);
            this.btnSerializar.Name = "btnSerializar";
            this.btnSerializar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSerializar.OnDisabledState.BorderRadius = 1;
            this.btnSerializar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSerializar.OnDisabledState.BorderThickness = 1;
            this.btnSerializar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSerializar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSerializar.OnDisabledState.IconLeftImage = null;
            this.btnSerializar.OnDisabledState.IconRightImage = null;
            this.btnSerializar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSerializar.onHoverState.BorderRadius = 1;
            this.btnSerializar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSerializar.onHoverState.BorderThickness = 1;
            this.btnSerializar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSerializar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSerializar.onHoverState.IconLeftImage = null;
            this.btnSerializar.onHoverState.IconRightImage = null;
            this.btnSerializar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSerializar.OnIdleState.BorderRadius = 1;
            this.btnSerializar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSerializar.OnIdleState.BorderThickness = 1;
            this.btnSerializar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSerializar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSerializar.OnIdleState.IconLeftImage = null;
            this.btnSerializar.OnIdleState.IconRightImage = null;
            this.btnSerializar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSerializar.OnPressedState.BorderRadius = 1;
            this.btnSerializar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSerializar.OnPressedState.BorderThickness = 1;
            this.btnSerializar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSerializar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSerializar.OnPressedState.IconLeftImage = null;
            this.btnSerializar.OnPressedState.IconRightImage = null;
            this.btnSerializar.Size = new System.Drawing.Size(153, 37);
            this.btnSerializar.TabIndex = 74;
            this.btnSerializar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSerializar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSerializar.TextMarginLeft = 0;
            this.btnSerializar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSerializar.UseDefaultRadiusAndThickness = true;
            this.btnSerializar.Click += new System.EventHandler(this.btnSerializar_Click);
            // 
            // FormMaestroClientes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(28)))), ((int)(((byte)(82)))));
            this.ClientSize = new System.Drawing.Size(1200, 862);
            this.Controls.Add(this.btnSerializar);
            this.Controls.Add(this.btnDeserializar);
            this.Controls.Add(this.btnChangeEncrypt);
            this.Controls.Add(this.btnLimpiarSeleccion);
            this.Controls.Add(this.lblCantClientes);
            this.Controls.Add(this.lblNumeroClientes);
            this.Controls.Add(this.btnModificar);
            this.Controls.Add(this.txtMail);
            this.Controls.Add(this.TxtDni);
            this.Controls.Add(this.TxtApellido);
            this.Controls.Add(this.TxtNombre);
            this.Controls.Add(this.DG_Clientes);
            this.Controls.Add(this.btnInicio);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.lblPrincipalGestionClientes);
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "FormMaestroClientes";
            this.Text = "FormMaestroClientes";
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DG_Clientes)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel lblPrincipalGestionClientes;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInicio;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLimpiarSeleccion;
        private System.Windows.Forms.Label lblCantClientes;
        private System.Windows.Forms.Label lblNumeroClientes;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModificar;
        private Bunifu.UI.WinForms.BunifuTextBox txtMail;
        private Bunifu.UI.WinForms.BunifuTextBox TxtDni;
        private Bunifu.UI.WinForms.BunifuTextBox TxtApellido;
        private Bunifu.UI.WinForms.BunifuTextBox TxtNombre;
        private Bunifu.UI.WinForms.BunifuDataGridView DG_Clientes;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangeEncrypt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDeserializar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSerializar;
    }
}